"""initial schema: filings, sections, xbrl_facts, raw_landings

Revision ID: 500af8f564f1
Revises: 
Create Date: 2026-06-07 14:01:08.269677
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500af8f564f1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('accession_no', sa.String(length=20), nullable=False),
    sa.Column('form', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=2), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('primary_doc', sa.String(length=255), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filings')),
    sa.UniqueConstraint('accession_no', name=op.f('uq_filings_accession_no'))
    )
    op.create_index(op.f('ix_filings_cik'), 'filings', ['cik'], unique=False)
    op.create_table('raw_landings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_path', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_landings')),
    sa.UniqueConstraint('source', 'content_hash', name='uq_raw_landings_dedup')
    )
    op.create_index(op.f('ix_raw_landings_content_hash'), 'raw_landings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_landings_source'), 'raw_landings', ['source'], unique=False)
    op.create_table('xbrl_facts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('accession_no', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('context_ref', sa.String(length=128), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=2), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xbrl_facts')),
    sa.UniqueConstraint('accession_no', 'tag', 'context_ref', name='uq_xbrl_facts_fact')
    )
    op.create_index('ix_xbrl_facts_lookup', 'xbrl_facts', ['cik', 'tag', 'fiscal_year'], unique=False)
    op.create_table('filing_sections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('filing_id', sa.BigInteger(), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name=op.f('fk_filing_sections_filing_id_filings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filing_sections'))
    )
    op.create_index(op.f('ix_filing_sections_filing_id'), 'filing_sections', ['filing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filing_sections_filing_id'), table_name='filing_sections')
    op.drop_table('filing_sections')
    op.drop_index('ix_xbrl_facts_lookup', table_name='xbrl_facts')
    op.drop_table('xbrl_facts')
    op.drop_index(op.f('ix_raw_landings_source'), table_name='raw_landings')
    op.drop_index(op.f('ix_raw_landings_content_hash'), table_name='raw_landings')
    op.drop_table('raw_landings')
    op.drop_index(op.f('ix_filings_cik'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
